#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  4 14:03:28 2020

2) Images: Checkerboard mask
In the British television game show Catchphrase, contestants have to identify an image. The image
is divided into 9 rectangular pieces, and each piece is revealed in turn until one of the contestants is
able to identify the image. You can see an example of the game here:
https://www.youtube.com/watch?v=qqb-j1cNPhQ
Write a Python module providing a function that can be used to create partially masked versions of
images, like in the show. The function should take an image object as its input and return a partially
masked version of that same image, in which some of the 9 rectangular regions of the image have
been made black. An integer input argument is used to determine how many of the 9 pieces of the
image are blacked out and how many are revealed.

Hints:
• You might find it easier to move some of the image processing steps into additional ‘helper
functions’, so that you can more easily test these steps separately.
• Not every image will have dimensions that are exactly divisible by 3 so as to produce equalsized
sections. You will need to decide on a means of dividing the image up into sections
that are as equal in size as possible.

@author: calypso
"""

# loading domains.
import os
import imageio

bgf
